### ISSUE TITLE
[Suggestion] Replace "Latest" Button

### ISSUE THREAD

**Issue by Xarmat-GitHub** [Daomephsta/LootTweaker-Docs#3]
When working with the Docs, the "latest" element blocks the "next" button.
http://prntscr.com/zynphb

It would be great if it can be replaced 20~30 pixels up.
Then the next button can be clicked without hazel.

**Comment by Xarmat-GitHub** [comment]
Oh, I see that there is also "next" on the top page, so this Suggestion is just a small addition and can be closed if not interested for you.

**Comment by Daomephsta** [comment]
The HTML and CSS of the docs are built using Sphinx from ReStructured Text files, so I don't have that level of control. 
In any case, it's a sticky element, so just scroll to move it out of the way.
